[package]

name = "gl-util"
version = "0.1.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[dependencies]
gl-raw = { path = "../gl-raw" }

[target.'cfg(target_os = "windows")'.dependencies]
user32-sys = "0.1"
winapi = "0.2.8"
