[package]
name = "polygon-math"
version = "0.1.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[features]
serde-impls = ["serde", "serde_derive"]

[dependencies]
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
